[package]
name = "fuzz"
version = "0.1.0"
authors = ["The TiKV Project Developers", "Chojan Shang <psiace@outlook.com>"]
publish = false

[dependencies]
afl = "0.8.0"
crc64fast-nvme = { path = ".." }
